server {
    listen 7000;
    server_name _;     # le server_name ne sert pas vraiment dans des containers derrière Traefik

    root /usr/share/nginx/html;
    index index.html;

    location = /env.js {
        default_type application/javascript;
        try_files $uri =404;
    }


    # Sert TOUT fichier statique ou index.html s'il n'existe pas
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Sert les fichiers qui existent dans static/ ou renvoie 404
    location ~* ^/static/ {
        try_files $uri =404;
    }

    # # Bloque direct les URLs /api côté frontend !
    # location /api {
    #     return 404;
    # }
    
    # Facultatif : renvoie une vraie page 404 si tu mets /usr/share/nginx/html/404.html
    error_page 404 /404.html;
}
