- name: Installer Docker et Docker Compose
  become: true
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: true

- name: Démarrer et activer Docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Ajouter l'utilisateur guillaume au groupe docker
  become: true
  ansible.builtin.user:
    name: guillaume
    groups: docker
    append: true

- name: Créer le dossier de monitoring
  ansible.builtin.file:
    path: /home/guillaume/monitoring
    state: directory
    owner: guillaume
    group: guillaume
    mode: '0755'

- name: copier le fichier prometheus.yml avec les variables
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /home/guillaume/monitoring/prometheus.yml
    owner: guillaume
    group: guillaume
    mode: '0644'

- name: Copier le fichier docker-compose.yml
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /home/guillaume/monitoring/docker-compose.yml
    owner: guillaume
    group: guillaume
    mode: '0644'

- name: Arrêter les services existants (si ils existent)
  ansible.builtin.shell: docker compose down
  args:
    chdir: /home/guillaume/monitoring
  ignore_errors: true

- name: Nettoyer les anciennes images si nécessaire
  ansible.builtin.shell: docker image prune -f
  when: monitoring_cleanup | default(false)

- name: Lancer Docker Compose pour Prometheus et Grafana
  ansible.builtin.command: docker compose up -d
  args:
    chdir: /home/guillaume/monitoring
  register: docker_compose_result

- name: Vérifier l'état des conteneurs
  ansible.builtin.shell: docker compose ps
  args:
    chdir: /home/guillaume/monitoring
  register: containers_status