- name: Create monitoring configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: '0755'
  loop:
    - /opt/monitoring/prometheus
    - /opt/monitoring/prometheus/console_libraries
    - /opt/monitoring/prometheus/consoles
    - /opt/monitoring/grafana/provisioning/datasources
    - /opt/monitoring/grafana/provisioning/dashboards
    - /opt/monitoring/grafana/dashboards
    - /opt/monitoring/grafana/dashboards/app
    - /opt/monitoring/grafana/dashboards/swarm
  when: inventory_hostname == groups['swarm_managers'][0]


- name: Generate Prometheus configuration
  template:
    src: templates/prometheus.yml.j2
    dest: /opt/monitoring/prometheus/prometheus.yml
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: '0644'
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Generate Grafana datasource configuration
  template:
    src: templates/grafana_datasource.yml.j2
    dest: /opt/monitoring/grafana/provisioning/datasources/prometheus.yml
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: '0644'
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Generate Grafana dashboard configuration
  template:
    src: templates/grafana-dashboard-provider.yml.j2
    dest: /opt/monitoring/grafana/provisioning/dashboards/default.yml
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: '0644'
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Copy Docker Swarm dashboard
  template:
    src: templates/docker-swarm-dashboard.json.j2
    dest: /opt/monitoring/grafana/dashboards/docker-swarm.json
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: '0644'
  when: 
    - inventory_hostname == groups['swarm_managers'][0]