services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: <PRIVATE_IP_MYSQL>
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 3306