# Configuration Base de Données
database:
  name: "sneakerportfolio"
  user: "guillaume"
  host: "localhost"
  port: "3306"
  container_name: "mysql"

# Variables pour les tâches (noms standard)
db_name: "{{ database.name }}"
db_user: "{{ database.user }}"
db_host: "{{ database.host }}"
db_port: "{{ database.port }}"

# Configuration backup MySQL
mysql_backup:
  container_name: "{{ database.container_name }}"
  db_name: "{{ database.name }}"
  db_user: "{{ database.user }}"
  db_password: "{{ vault_db_password }}"
  s3_bucket: "mysql-backup-projet-devops-gle"

# Collecteurs supplémentaires pour les serveurs de base de données
node_exporter_enabled_collectors:
  - systemd
  - textfile
  - processes
  - interrupts
  - tcpstat
  - conntrack
  - diskstats
  - filesystem
  - meminfo
