---
- name: Installer Certbot + Google Cloud plugin
  apt:
    name:
      - certbot
      - python3-certbot-dns-google
    state: present
    update_cache: yes
  become: true

- name: Vérifier la propagation DNS des sous-domaines (Google resolver)
  shell: "dig +short {{ item.subdomain }}.{{ domain_name }} @8.8.8.8 A"
  delegate_to: localhost
  register: dns_results
  loop: "{{ dns_services }}"
  when: item.enabled
  changed_when: false

- name: Afficher l'état DNS des services
  debug:
    msg: >
      "{{ item.subdomain }}.{{ domain_name }} pointe vers
        {{ dns_results.results[loop.index0].stdout | default('aucune IP') }}"
  loop: "{{ dns_services }}"
  when: item.enabled
  loop_control:
    loop_var: item

- name: Détecter l'IP du Load Balancer depuis Hostvars
  set_fact:
    lb_ip: "{{ hostvars[inventory_hostname]['lb_ip'] | default(lookup('env','LB_IP')) }}"

- name: Afficher l'IP du Load Balancer pour info
  debug: var=lb_ip

- name: Générer le certificat wildcard via DNS Google
  shell: >
    certbot certonly --dns-google
      --dns-google-credentials "/opt/gcp-service-account.json"
      --dns-google-propagation-seconds 120
      -d *.{{ domain_name }}
      -d {{ domain_name }}
      --email {{ ssl_email }}
      --agree-tos --non-interactive
  args:
    creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
  when: ssl_enabled|bool
