app_services:
  - traefik
  - frontend
  - backend
  - database
  - prometheus
  - grafana

project_name: "projet-devops-gle"
app_directory: "/opt/{{ app_name }}"
gcp_credentials_file: "/home/guillaume/projet-DevOps-gle/terraform_gcp/credentials/gcp-sa-key.json"
gcp_swarm_sa_json: "{{ app_directory }}/gcp-service-account.json"

frontend_port: 7000
backend_port: 5000
frontend_replicas: 2
backend_replicas: 2

db_name: "sneakerportfolio"
db_user: "guillaume"
db_host: "database"
db_port: "3306"

api_domain: "api.{{ domain_name }}"
grafana_domain: "grafana.{{ domain_name }}"
prometheus_domain: "prometheus.{{ domain_name }}"
traefik_domain: "traefik.{{ domain_name }}"
grafana_admin_user: "admin"
prometheus_retention_time: "15d"

domain_name: "sneakerportfolio.eu"
app_environment: production
app_version: "v1.0.0"

api_rate_limit: 60