---
all:
  vars:
    ansible_user: guillaume
    ansible_ssh_private_key_file: ~/.ssh/gcp-ssh-key
    ansible_ssh_common_args: '-o ProxyCommand="ssh -i ~/.ssh/gcp-ssh-key -W %h:%p -q guillaume@34.38.188.214"'
  
  children:
    frontend:
      hosts:
        frontend1:
          ansible_host: 10.0.2.5
    
    reverse_proxy:
      hosts:
        reverse_proxy1:
          ansible_host: 34.38.188.214
      vars:
        ansible_port: 22
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    backend:
      hosts:
        backend1:
          ansible_host: 10.0.2.2
    
    database:
      hosts:
        database1:
          ansible_host: 10.0.2.3
    
    monitoring:
      hosts:
        monitoring1:
          ansible_host: 10.0.2.4

    web:
      children:
        frontend: {}
        reverse_proxy: {}
    
    infrastructure:
      children:
        backend: {}
        database: {}
        monitoring: {}
