[frontend]
10.0.2.3 ansible_user=guillaume

[reverse_proxy]
34.38.190.28 ansible_user=guillaume

[backend]
10.0.2.4 ansible_user=guillaume

[database]
10.0.2.5 ansible_user=guillaume

[monitoring]
10.0.2.2 ansible_user=guillaume

[all:vars]
ansible_ssh_private_key_file=~/.ssh/gcp-ssh-key.pem
ansible_ssh_common_args='-o ProxyCommand="ssh -i ~/.ssh/gcp-ssh-key.pem -W %h:%p -q guillaume@34.38.190.28"'

[bastion]
bastion-server ansible_host=34.38.190.28 

[bastion:vars]
ansible_user=guillaume
ansible_port=22
ansible_ssh_common_args=''
