# INVENTAIRE DOCKER SWARM

# Variables globales
[all:vars]
ansible_user=deploy
ansible_ssh_private_key_file=/home/guillaume/.ssh/gcp-ssh-key
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o ProxyJump=deploy@35.195.240.140"
load_balancer_ip=34.8.188.63
swarm_leader_ip=10.0.2.4
bastion_public_ip=35.195.240.140
cluster_total_nodes=5
cluster_manager_count=3
cluster_worker_count=2

# MANAGERS
[swarm_managers]
manager_1 ansible_host=10.0.2.4 swarm_role=manager swarm_leader=true
manager_2 ansible_host=10.0.2.5 swarm_role=manager swarm_leader=false
manager_3 ansible_host=10.0.2.6 swarm_role=manager swarm_leader=false

# WORKERS
[swarm_workers]
worker_1 ansible_host=10.0.2.2 swarm_role=worker
worker_2 ansible_host=10.0.2.3 swarm_role=worker

[swarm_cluster:children]
swarm_managers
swarm_workers

[swarm_nodes:children]
swarm_managers
swarm_workers

[swarm_deploy]
manager_1

[bastion]
swarm_bastion ansible_host=35.195.240.140 private_ip=10.0.2.4 lb_ip=34.8.188.63 swarm_role=bastion

[bastion:vars]
ansible_ssh_common_args="-o StrictHostKeyChecking=no"
