- name: Configure all servers with node_exporter
  hosts: all
  become: true
  roles:
    - node_exporter
  vars_files:
    - host_vars/monitoring.yml
    - group_vars/database.yml
    - defaults/main.yml

- name: Ensure user guillaume exists and SSH key is deployed
  hosts: all
  become: true
  tasks:
    - name: Créer l'utilisateur guillaume
      user:
        name: guillaume
        state: present

    - name: Créer le dossier .ssh
      file:
        path: /home/guillaume/.ssh
        state: directory
        owner: guillaume
        group: guillaume
        mode: 0700

    - name: Déposer la clé publique
      authorized_key:
        user: guillaume
        key: "{{ lookup('file', '~/.ssh/gcp-ssh-key.pub') }}"
        state: present

- name: Déployer le frontend
  hosts: frontend
  become: true
  roles:
    - frontend
  vars_files:
    - host_vars/frontend-vm.yml
    - group_vars/all.yml

- name: Déployer le backend
  hosts: backend
  become: true
  roles:
    - backend
  vars_files:
    - group_vars/vault.yml
    - group_vars/all.yml
    - host_vars/backend-vm.yml

- name: Déployer la base de données
  hosts: database
  become: true
  roles:
    - database
  vars_files:
    - group_vars/*.yml

- name: Déployer Prometheus & Grafana
  hosts: monitoring
  become: true
  roles:
    - monitoring
  vars_files:
    - host_vars/monitoring.yml
    - group_vars/all.yml
    - defaults/main.yml

- name: Déployer le reverse proxy NGINX
  hosts: reverse_proxy
  become: true
  roles:
    - reverse-proxy
  vars_files:
    - group_vars/all.yml

