- name: Install Nginx + Certbot
  apt:
    name:
      - nginx
      - python3-certbot-nginx
    state: present
    update_cache: yes

- name: Copy nginx.conf file
  copy:
    src: "{{ playbook_dir }}/../../reverse-proxy/nginx.conf"
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: Reload NGINX

- name: Start NGINX
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Wait for Website Online (for certbot)
  uri:
    url: 
    method: GET
  register: result
  retries: 10
  delay: 10
  until: result.status == 200

- name: Get a SSL certificate
  command: >
    certbot --nginx --non-interactive --agree-tos
    --email you@example.com -d monapp.example.com
  args:
    creates: /etc/letsencrypt/live/monapp.example.com/fullchain.pem

- name: Reload NGINX
  systemd:
    name: nginx
    state: reloaded