# Variables globales partagées
project_name: "projet-devops-gle"
app_version: "v1.0.0"
app_directory: "/opt/{{ project_name }}"
app_environment: production
ssh_user: "deploy"
ssh_public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/gcp-ssh-key.pub') }}"
# ssh_public_key: /home/guillaume/.ssh/gcp-ssh-key.pub
gcp_credentials_file: "{{ lookup('env','PWD') }}/terraform_gcp/credentials/gcp-sa-key.json"
gcp_swarm_sa_json: "{{ app_directory }}/gcp-service-account.json"

domain_name: "sneakerportfolio.eu"
api_domain: "api.sneakerportfolio.eu"
grafana_domain: "grafana.sneakerportfolio.eu"
prometheus_domain: "prometheus.sneakerportfolio.eu"
traefik_domain: "traefik.sneakerportfolio.eu"

project_id: "geometric-watch-455507-m6"
swarm_lb_ip: "{{ hostvars[groups['swarm_managers'][0]]['ansible_default_ipv4']['address'] }}"

docker_hub_username: "guigan713"
docker_hub_password: "{{ vault_docker_hub_password }}"

node_exporter_port: 9100
node_exporter_version: "1.7.0"
prometheus_retention_time: "15d"

db_host: "database"
db_port: 3306
db_name: "sneakerportfolio"
db_user: "guillaume"
db_service_name: "{{ project_name }}_database"

db_backup_enabled: true
db_backup_schedule: "0 2 * * *"  # Tous les jours à 2h du matin
db_backup_retention_days: 30

environment: "production"
api_rate_limit: "100"

frontend_replicas: 2
backend_replicas: 2

bucket_name: "{{ project_name }}-backups"
mysql_root_password: "{{ vault_db_root_password }}"

backend_cors_origins: 
  - "http://{{ domain_name }}"
  - "https://{{ domain_name }}"


deploy_version: "{{ app_version }}"
