- name: Installer Docker et Docker Compose
  become: true
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: true

- name: Démarrer et activer Docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Ajouter l'utilisateur ubuntu au groupe docker
  become: true
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true

- name: Create Database Directory
  file:
    path: /home/ubuntu/database
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy MySQL Services Files
  copy:
    src: "{{ playbook_dir }}/../../database/"
    dest: /home/ubuntu/database/
    owner: ubuntu
    group: ubuntu
    mode: preserve

- name: Exec Compose for Database
  command: docker-compose up -d
  args:
    chdir: /home/ubuntu/database

- name: Wait for MySQL to be ready
  wait_for:
    port: 3306
    host: localhost
    timeout: 60

- name: Create database user
  mysql_user:
    name: guillaume
    password: "{{ vault_db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: "%"
    login_host: localhost
    login_user: root
    login_password: "{{ vault_db_root_password }}"
  become: yes

- name: Copier le script de backup MySQL
  template:
    src: mysql_backup.sh.j2
    dest: /usr/local/bin/mysql_backup.sh
    mode: '0700'
  become: true

- name: Ajouter la tâche cron
  cron:
    name: "Backup SQL chaque jour a 2h"
    minute: "0"
    hour: "2"
    job: "/usr/local/bin/mysql_backup.sh >> /var/log/mysql_backup.log 2>&1"
    user: root