name: Build & deploy projet DevOps

on:
  push:
    branches:
      - build

jobs:
  build-frontend:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build Backend Image
        run: |
          docker build -t backend:latest ./backend

      - name: Build Frontend Image
        run: |
          docker build -t frontend:latest ./frontend
